### PR TITLE
Fix section date time

### PR DESCRIPTION
**Pull request by idanizi-panw**
## Description:
- Remove "Date:" prefix
- Fix datetime format

## Before
image

## After:
image

### CODE REVIEW

**Comment by idanizi-panw** [comment]
https://github.com/demisto/etc/issues/42120

**Comment by asafshen** [comment]
@idanizi-panw build fails, can we fix?

**Comment by idanizi-panw** [comment]
@yonatan-roth @Bars92 `Generate test template layout report` test is unstable, we need to fix that

**Review by asafshen — APPROVED** [review]
👍

**Pull request merged**
